### ISSUE TITLE
Use of unresolved identifier 'withUnsafeBytes'

### ISSUE THREAD

**Issue by awatson1978** [500LABS/HotBox#16]
Hi there,
Trying to run the example, and getting the following error:
![screen shot 2017-10-16 at 12 20 32 am](https://user-images.githubusercontent.com/675910/31596436-29b906b4-b208-11e7-96f3-1a843a5216e2.png)

Pretty sure there's some sort of core library that's not being imported that provides the `withUnsafeBytes()` function/method.  Any thoughts on what it might be?  Or how to add it in?

**Comment by Jonovono** [comment]
hmm it appears to be built in: https://developer.apple.com/documentation/swift/array/2635991-withunsafebytes

What version of Xcode are you on?

**Comment by awatson1978** [comment]
Ah, nice.  I'm on XCode 8.0, but I'm not sure I have the Swift libraries installed.  Will look into that as soon as I get into work.

**Comment by awatson1978** [comment]
Yup, that was it.  7 hours and 20GB later, I've upgraded OS, Safari, XCode, etc. etc.  And everything compiles without any problems.  Thank you much!  :)

**Comment by Jonovono** [comment]
haha glad to hear @awatson1978 !
