### ISSUE TITLE
Bridging Header?

### ISSUE THREAD

**Issue by krokhale** [500LABS/HotBox#17]
Any documentation for the steps to add a bridging header?

**Comment by Jonovono** [comment]
So what you can do is create a .h file and call it "<Appname>-Bridging-Header.h" and then in your Info.plist there should be a key `Objective-C Bridging Header` and give it the value of "<Appname>-Bridging-Header.h"

Hope that helps.

**Comment by krokhale** [comment]
Also cloned the repo and followed this:

<img width="553" alt="screen shot 1" src="https://user-images.githubusercontent.com/173148/32142002-62bf6f96-bcb4-11e7-8d05-56ad66fefe4c.png">


And ran it, got this:

<img width="351" alt="screen shot 2017-10-29 at 1 39 19 pm" src="https://user-images.githubusercontent.com/173148/32142006-6d1ca65c-bcb4-11e7-9f98-913d48b92bfc.png">


What am i missing?

**Comment by krokhale** [comment]
ok resolved it.

Needed to add react and react-native as dependencies in the HotBox/package.json

Bam!

I can use the Example as the base app for now, It would be really cool though if adding the bridging headers was somehow automated. Dealing with Xcode is a pain.

Thanks!
