### ISSUE TITLE
Exception thrown while executing UI Block: CALayer bounds contains NAN

### ISSUE THREAD

**Issue by mozilla-rowvigor** [500LABS/HotBox#18]
Hi, I'm trying to load the publisher and I'm receiving this error. How can I fix it? 

![screen shot 2017-10-19 at 12 49 47 pm](https://user-images.githubusercontent.com/25875372/31788465-0434a698-b4cc-11e7-9417-486ec7a5cf8d.png)

Also, when I load the subscriber, I'm not receiving a subscriber id. Do i need the publisher loaded before receiving a subscriber id?

Moses

**Comment by Jonovono** [comment]
I've seen this exact issue but I can't seem to recall what it was.

Some options/ideas:

1. Make sure you set a width, height on Publisherview: `<PublisherView  style={{width: 100, height: 100}} />`
2. Upload a simple project reproducing the issue and i'll find out why.

Can you expand on what you mean by 'when I load the subscriber, I'm not receiving a subscriber id' ? How are you loading the subscriber? You should get a streamId which is the subscriberId when you listen on `subscriberDidConnect` and you can then use that to feed into <SubscriberView streamId={streamId} />

Hope that helps! If you can't figure it out for sure just upload a sample repo with the code giving you problems and I can dig in easier.

**Comment by mozilla-rowvigor** [comment]
Hi Jordan,

Thanks for responding. Your recommendation to the first issue solved that problem. 

Here is another issue. I ran the app from the publisher perspective using my iPhone connected to xcode. This response was that I only see a white screen with this output in the debugger window repeating. I’m not quite sure how to fix it.

Moses

**Comment by Jonovono** [comment]
With which output? Did you mean to paste something ? :p

**Comment by mozilla-rowvigor** [comment]
Yes, here it is .

The error says “Failed to bind EagleDrawable

**Comment by mozilla-rowvigor** [comment]
I was able to fix my own issue “Failed to bind EagleDrawable”. It was related to my setting the screen size within RN, but I have one additional issue. I’m able to connect both devices and listen to audio from publisher to the subscriber and back. However, I only see a white screen. There is no video. Do you have any thoughts on how I could debug?

M

**Comment by Jonovono** [comment]
Hmm, i'm not sure. Can you upload the project? i'll take a look. I havn't experienced a white screen before.

**Comment by mozilla-rowvigor** [comment]
Hi Jordan, 

I got everything working. The key issue was my confusion of how everything works on Tokbox, my mis understating of subscriber and publisher. Only until after reading through this document https://tokbox.com/developer/guides/basics/ <https://tokbox.com/developer/guides/basics/>, I had a clear understanding that a single user is  both a subscriber as well as a publisher. Also, I was testing the publisher view using the IOS simulator, because I assume the simulator doesn’t have a camera. It only runs the subscriber view. 

Moses

**Comment by Jonovono** [comment]
Ah, great to hear!
