### ISSUE TITLE
`sessionStreamCreated` needs a stream type identifier

### ISSUE THREAD

**Issue by deqyd** [500LABS/HotBox#4]
Hey Guys,

So awesome job so far! Loving it! However, I have ran into a problem with the `sessionStreamCreated`. There needs to be a way to identify the type of stream it is. An example from the tokbox sdk gives you access to the `stream` prop where you can find the `videoType` or `hasAudio` params:
```
session.on("streamCreated", function(event) {
    event.stream...
```

While I don't exactly need access to the `stream`  object, getting params like this and similar is paramount. 
Thanks

**Comment by Jonovono** [comment]
Hello @deqyd , glad you are finding it useful!

What you are requesting makes sense. Some of the code is still pretty specific to our use case and needs to be further generalised out to cover the complete TokBox SDK.

I'll try and get this in in the next release or so but feel free to open a PR and also open any more tickets of things you'd like.

**Comment by deqyd** [comment]
Awesome. Thanks.

**Comment by george-lim** [comment]
On it.

**Comment by deqyd** [comment]
@george-lim sweet! What will you do? Expose the `stream` obj?

**Comment by george-lim** [comment]
Unfortunately, I cannot do that because when I bridge from Swift to React Native, it only accepts certain parameter types to be sent over (eg. NSArray, NSDictionary, NSNumber). However, what I can do is make a dictionary containing all of the properties of the stream and send that over to you.

**Comment by deqyd** [comment]
@george-lim sounds perfect man! Thank you.

**Comment by george-lim** [comment]
Okay, it's done. I have also given more information to you in sessionConnectionCreated as well. The following changes were made:

connectionCreated now returns a dictionary with:
"connectionId" -> String representing connection id
"creationTime" -> time in Epoch Unix
"data" -> String representing data

streamCreated now returns a dictionary with:
"streamId" -> String representing stream id
"creationTime" -> time in Epoch Unix
"hasAudio" -> Bool
"hasVideo" -> Bool
"name" -> String representing stream name
"videoDimensions" -> Dictionary with "width" and "height" keys and their corresponding number values
"videoType" -> String (either "camera" or "screen")

**Comment by deqyd** [comment]
@george-lim you're the man!

**Comment by george-lim** [comment]
Glad to help, let me know if you need anything else :)
