### ISSUE TITLE
No Such module 'RxSwift'

### ISSUE THREAD

**Issue by mozilla-rowvigor** [500LABS/HotBox#7]
I created an RN test app, installed Hotbox and it's required Podfile. In addition to inserting the bridge file, but after building, the compiler outputted a  "No Such module 'RxSwift'" error. 

I followed the same steps with the example file and observed the same error. How would I fix this issue? 

==================================================================
target 'TokBox' do

  use_frameworks!

  pod 'RxSwift'
  pod 'OpenTok'

end

**Comment by Jonovono** [comment]
Did you run `pod install` in the `ios` directory?

**Comment by mozilla-rowvigor** [comment]
Yes, I ran pod install in the ios directory.

**Comment by Jonovono** [comment]
@mozilla-rowvigor So I was able to reproduce your issue if I build the `Example.xcodeproj/`. Make sure you open the `Example.xcworkspace/`.

If you still have the issue do you see this when you run `pod install`?

```
Downloading dependencies
Installing OpenTok (2.11.3)
Installing RxSwift (3.6.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

**Comment by mozilla-rowvigor** [comment]
Ok, so ran pod install in the Example/ios folder. Here was my output

Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.3.1) is higher than the version of the current executable (1.2.1). Incompatibility issues may arise.
Downloading dependencies
Installing OpenTok (2.11.3)
Installing RxSwift (3.6.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.

[!] Automatically assigning platform ios with version 8.0 on target Example because no platform was specified. Please specify a pla(rv_loca(rv_local) rowv(rv_loc(rv(r(((

**Comment by Jonovono** [comment]
Hmm, ya that looks good. And if you build `Example.xcworkspace/` you still get that issue?

**Comment by mozilla-rowvigor** [comment]
I recompiled the example. This time I didn't get any issues. I'll try to recreate my project and follow instructions again.

**Comment by Jonovono** [comment]
Awesome, good luck.

**Comment by mozilla-rowvigor** [comment]
So I recreated the project, installed the Pod, imported the Swift file, and created the bridge file. I see the same error. I think there is a missing step. Not sure. Do I need to manually include the RxSwift library?

**Comment by Jonovono** [comment]
I just created a blank project and it builds fine. Maybe zip up your project and post here if you can @mozilla-rowvigor. I'll take a look. Should work. You are building your workspace project right?

**Comment by mozilla-rowvigor** [comment]
I realized that I was building in the wrong workspace. I was using **xcodeproj** instead of **xcworkspace**. I'm receiving this error. 

![screen shot 2017-09-03 at 10 01 38 am](https://user-images.githubusercontent.com/25875372/30004561-19cd7a54-908f-11e7-96b2-adf2af400c79.png)

**Comment by Jonovono** [comment]
That might be a bridging header issue? You created a bridging header? In Build Settings -> Objective-C bridging Header is set too?

**Comment by mozilla-rowvigor** [comment]
Ok, I got everything to work. I just included the headers. Thanks for your help.

**Comment by Jonovono** [comment]
Excellent! Glad it's working. Let me know if you have any questions :)
