### ISSUE TITLE
React Native App fails to launch with Hotbox installed

### ISSUE THREAD

**Issue by mozilla-rowvigor** [500LABS/HotBox#8]
I created a new React Native project. Installed the HotBox library. Everything compiles successfully. However, within the ios simulator, the app launches but doesn't load into the welcome to React Native screen instead it quietly closes. I have not modified any code other than linked the Hotbox libraries. Is there any additional setup I need to complete successfully launch the app?

Moses

**Comment by Jonovono** [comment]
Does the project crash in xcode?

Sounds related to this: https://github.com/facebook/react-native/issues/15762

**Comment by mozilla-rowvigor** [comment]
No, I compiled useing the RN compile command for IOS.

I just compiled using xcode. It completed successfully. After launching the simulator, again it crashed. Here is the traceback message. 


2017-09-04 13:26:53.009 [info][tid:main][RCTCxxBridge.mm:188] Initializing <RCTCxxBridge: 0x6080001bf2c0> (parent: <RCTBridge: 0x6000000ae280>, executor: (null))
2017-09-04 13:26:53.065 [warn][tid:main][RCTBridge.m:114] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2017-09-04 13:26:53.101 [info][tid:main][RCTRootView.m:301] Running application Tok ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-09-04 13:26:53.787 Tok[41141:2132130] -[NSTaggedPointerString unsignedIntValue]: unrecognized selector sent to instance 0xa313839333930327
2017-09-04 13:26:53.839 Tok[41141:2132130] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString unsignedIntValue]: unrecognized selector sent to instance 0xa313839333930327'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109c46b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010d1a4141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109cb6134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000109bcd840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000109bcd3b8 _CF_forwarding_prep_0 + 120
	5   Tok                                 0x000000010870cb34 -[RCTMultipartStreamReader emitProgress:contentLength:final:callback:] + 244
	6   Tok                                 0x000000010870d32a -[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:] + 1610
	7   Tok                                 0x000000010875cc5c -[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:] + 444
	8   CFNetwork                           0x000000010d846c51 __88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke + 51
	9   Foundation                          0x000000010a989237 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	10  Foundation                          0x000000010a988f3b -[NSBlockOperation main] + 101
	11  Foundation                          0x000000010a9876f7 -[__NSOperationInternal _start:] + 627
	12  Foundation                          0x000000010a98347c __NSOQSchedule_f + 198
	13  libdispatch.dylib                   0x000000010fbb305c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010fb9194f _dispatch_queue_serial_drain + 221
	15  libdispatch.dylib                   0x000000010fb92669 _dispatch_queue_invoke + 1084
	16  libdispatch.dylib                   0x000000010fb94ec4 _dispatch_root_queue_drain + 634
	17  libdispatch.dylib                   0x000000010fb94bef _dispatch_worker_thread3 + 123
	18  libsystem_pthread.dylib             0x000000010ff4a712 _pthread_wqthread + 1299
	19  libsystem_pthread.dylib             0x000000010ff4a1ed start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by Jonovono** [comment]
Yup, that's the same error I saw the other day. Follow the link I posted
