### ISSUE TITLE
[Not a bug] linking HotBox to my web version

### ISSUE THREAD

**Issue by masudhossain** [500LABS/HotBox#9]
I cloned this [repo](https://github.com/aullman/opentok-meet) and inputed my own credentials in to get it working. 

I would like the HotBox examples room to be the same room as my websites room (let's say tokbox-example.com/room123). 

Any idea how I would link it together? 

Is the websites 'room123' considered it's sessionId? and so if I input 'room123' for the sessionId on HotBox, will it will link up correctly?

**Comment by Jonovono** [comment]
Where does `room123` come from?

I usually generate the sessionId and token on tokbox site for testing:

<img width="789" alt="screen shot 2017-09-05 at 2 46 21 pm" src="https://user-images.githubusercontent.com/775808/30077199-172234e6-9249-11e7-93fa-404a12260bb6.png">

**Comment by Jonovono** [comment]
@masudhossain I think I see. In that project it uses `room123` to make a request somewhere to generate the token and session id.

In this code:

```
    res.format({
      json: function() {
        var goToRoom = function(err, sessionId, apiKey, secret) {
          if (err) {
            console.error('Error getting room: ', err);
            res.send({
              error: err.message
            });
          } else {
            res.set({
              'Access-Control-Allow-Origin': '*'
            });
            var otSDK = ot;
            if (apiKey && secret) {
              otSDK = new OpenTok(apiKey, secret);
            }
            res.send({
              room: room,
              sessionId: sessionId,
              apiKey: (apiKey && secret) ? apiKey : config.apiKey,
              p2p: RoomStore.isP2P(room),
              token: otSDK.generateToken(sessionId, {
                role: 'publisher'
              })
            });
          }
        };
        RoomStore.getRoom(room, apiKey, secret, goToRoom);
      },
```

You could log out the sessionId and token for that room.

**Comment by masudhossain** [comment]
So you're saying get the sessionId and Token from the other repo and than put it into HotBox's settings for sessionId and Token? 

And than it'll sync up together ?

What about the room name?

**Comment by Jonovono** [comment]
sessionId, apiKey, and token should be all that's needed.

**Comment by masudhossain** [comment]
So i was able to grab the sessionId, apiKey, and token correctly to create new sessions of users. 

But do you guys have a way to completely remove/disconnect a user from a session on button click? 

I tried the `session.disconnectAllSessions()` but i get this error: http://prntscr.com/gnsx8e
